### ISSUE TITLE
lon/lat minutes are malformed when there's less than 4 decimals

### ISSUE THREAD

**Issue by dbursem** [adafruit/Adafruit-GPS-Library#50] opened 2015-09-13 00:47 UTC
I used a NMEA simulator ( https://chrome.google.com/webstore/detail/nmea-simulator/dfhcgoinjchfcfnnkecjpjcnknlipcll ) to test my setup, but it outputs minutes with 3 decimals instead of the expected 4. 
This messed up my coordinates so I dug into the library and found that it always expects at least 4 decimals (on line 77, 106, 190 and 219). 
Also, more precise coordinates (5 or more decimals) will be truncated. 

I tried comming up with a solution but I need some sleep first. Hopefully I'll get back to this.

**Comment by tdicola** [comment] 2015-09-22 03:40
Ah thanks for raising the issue and digging in to find the cause.  Yeah it's a bit of a trade-off in the parsing logic--to keep it simple it just expects the 4 digits that the ultimate GPS modules send (for example a string like `$GPGGA,064951.000,2307.1256,N,12016.4438,E,1,8,0.95,39.9,M,17.8,M,,*65 `).  It's a good future to-do to make it more general and see if it can be done so without a significant hit to the code size.  For now it's a low priority so I'll close this, thanks for investigating though!

**Closed by tdicola** 2015-09-22 03:40 UTC
